In [1]:
import pandas as pd
from data_profiling import ProfileReport

In [2]:
excel_file = pd.ExcelFile("Adidas_Sales_Data.xlsx")
print(excel_file.sheet_names)

['Data Sales Adidas']

In [3]:
df = pd.read_excel(excel_file)
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,Adidas Sales Database,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
4,NaN,Foot Locker,1185732,2020-01-01 00:00:00,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000,0.5,In-store

In [4]:
df = pd.read_excel(excel_file, header = 4)
df.head()

,Unnamed: 0,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,NaN,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store
1,NaN,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store
2,NaN,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store
3,NaN,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store
4,NaN,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store

In [8]:
df.columns

Index(['Unnamed: 0', 'Retailer', 'Retailer ID', 'Invoice Date', 'Region',
       'State', 'City', 'Product', 'Price per Unit', 'Units Sold',
       'Total Sales', 'Operating Profit', 'Operating Margin', 'Sales Method'],
      dtype='object')

In [9]:
df.columns

Index(['Unnamed: 0', 'Retailer', 'Retailer ID', 'Invoice Date', 'Region',
       'State', 'City', 'Product', 'Price per Unit', 'Units Sold',
       'Total Sales', 'Operating Profit', 'Operating Margin', 'Sales Method'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        0 non-null      float64
 1   Retailer          9648 non-null   object
 2   Retailer ID       9648 non-null   int64
 3   Invoice Date      9648 non-null   datetime64[ns]
 4   Region            9648 non-null   object
 5   State             9648 non-null   object
 6   City              9648 non-null   object
 7   Product           9648 non-null   object
 8   Price per Unit    9648 non-null   float64
 9   Units Sold        9648 non-null   int64
 10  Total Sales       9648 non-null   float64
 11  Operating Profit  9648 non-null   float64
 12  Operating Margin  9648 non-null   float64
 13  Sales Method      9648 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(2), object(6)
memory usage: 1.0+ MB

In [11]:
df.shape

(9648, 14)

In [12]:
df.drop(columns = 'Unnamed: 0', inplace = True)

In [14]:
df.head()

(9648, 13)

In [15]:
df.describe()

,Retailer ID,Invoice Date,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin
count,9.648000e+03,9648,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000
mean,1.173850e+06,2021-05-10 15:20:44.776119296,45.216625,256.930037,93273.437500,34425.244761,0.422991
min,1.128299e+06,2020-01-01 00:00:00,7.000000,0.000000,0.000000,0.000000,0.100000
25%,1.185732e+06,2021-02-17 00:00:00,35.000000,106.000000,4254.500000,1921.752500,0.350000
50%,1.185732e+06,2021-06-04 00:00:00,45.000000,176.000000,9576.000000,4371.420000,0.410000
75%,1.185732e+06,2021-09-16 00:00:00,55.000000,350.000000,150000.000000,52062.500000,0.490000
max,1.197831e+06,2021-12-31 00:00:00,110.000000,1275.000000,825000.000000,390000.000000,0.800000
std,2.636038e+04,NaN,14.705397,214.252030,141916.016727,54193.113713,0.097197

In [16]:
df.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

%|                                                                                           | 0/13 [00:00<?, ?it/s]
%|██████▍                                                                            | 1/13 [00:00<00:02,  5.11it/s]
%|████████████▊                                                                      | 2/13 [00:00<00:01,  6.36it/s]
%|███████████████████▏                                                               | 3/13 [00:00<00:01,  7.30it/s]
%|██████████████████████████████████████▎                                            | 6/13 [00:00<00:00, 13.54it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 15.85it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [17]:
avg_price = df["Price per Unit"].mean()
avg_price

np.float64(45.21662520729685)

In [20]:
regions = df["Region"].nunique()
regions

5

In [21]:
total_trans = df["Invoice Date"].count()
total_trans

np.int64(9648)

In [22]:
df["Total_Sales"] = df["Units Sold"] * df["Price per Unit"]

In [23]:
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Total_Sales
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store,60000.0
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store,50000.0
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store,40000.0
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store,38250.0
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store,54000.0

In [32]:
df.groupby(["Region"])[list(df.select_dtypes('number').columns)].agg('mean')

,Retailer ID,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Total_Sales
Region,,,,,,,
Midwest,1.187017e+06,40.362179,209.047543,72542.980235,28211.189359,0.435272,8907.283120
Northeast,1.185310e+06,46.691498,210.976010,78419.220118,28628.193455,0.410450,10554.826178
South,1.188168e+06,38.236690,284.872685,83717.118634,35380.789392,0.466898,11923.238426
Southeast,1.159127e+06,50.183007,332.516340,133309.833333,49473.379657,0.419167,17462.774510
West,1.149912e+06,49.941176,280.631127,110270.907680,36605.149734,0.396691,14884.051062