# Introduction to Pandas
##### Pandas is a python library built on Numpy for data cleaning and analysis. It can be used to read very large data set. We start by installing Pandas

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
import pandas as pd

In [9]:
pd.__version__
#prints the version of pandas used

'2.2.3'

Pandas is made up of two main components which are Series, and DataFrame. A pandas serie is like an excel spreadsheet table, while a DataFrame is like the entire spreedsheet

In [10]:
countries = pd.Series(["Nigeria", "Ghana", "Kenya", "Ivory Coast", "Niger", "Benin"])
countries

0        Nigeria
1          Ghana
2          Kenya
3    Ivory Coast
4          Niger
5          Benin
dtype: object

The above line created a pandas series which is like a single column in a spreadsheet

In [11]:
columns_header = ["delivery_id", "item", "time_taken", "status"]
delivery_data = pd.DataFrame(
    [
        [101, "Rice", 35, "Delivered" ],
        [102, "Beans", 28, "Delivered"],
        [103, "Garri", 70, "Not Delivered"],
        [104, "Potato", 59, "Delivered"]
    ],
    columns = columns_header
)

delivery_data

   delivery_id    item  time_taken         status
0          101    Rice          35      Delivered
1          102   Beans          28      Delivered
2          103   Garri          70  Not Delivered
3          104  Potato          59      Delivered

The above code cell creates a Pandas dataframe using list but we have to create the columns name seperately which make the entire process really complicated

In [12]:
dataset = pd.DataFrame(
    [
        {
            "name": "Odey Divine",
            "role": "Data Scientist",
            "salary": "$50,000"
        },
        {
            "name": "Blessing Odey",
            "role": "Product Designer",
            "salary": "$10,000"
        },
        {
            "name": "Victory Osang",
            "role": "Product Manager",
            "salary": "$7,000"
        }
    ]
)

dataset

            name              role   salary
0    Odey Divine    Data Scientist  $50,000
1  Blessing Odey  Product Designer  $10,000
2  Victory Osang   Product Manager   $7,000

The above code cell creates a DataFrame which acts as an spreedsheet with rows and columns. But here the data is stored in form of **JSON** or **Python Dictionaries** and this is a more compact way of data entry compared to List of List

In [21]:
student_record = pd.DataFrame(
    {
        "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109],
        "name": ["Divine Odey", "Blessing Odey", "Victory Osang", "Daniel Bullem", "Maxwell Ogon", "Praise Bullem", " " , "Flourish Osang", "Joel Osang"],
        "score": [99, 97, 90, 89, 99, 96, 91, 91, 90]
    }
)

student_record

   student_id            name  score
0         101     Divine Odey     99
1         102   Blessing Odey     97
2         103   Victory Osang     90
3         104   Daniel Bullem     89
4         105    Maxwell Ogon     99
5         106   Praise Bullem     96
6         107                     91
7         108  Flourish Osang     91
8         109      Joel Osang     90

This is the most efficient way of creating a dataframe in pandas

In [22]:
del student_record["score"]

# the above line of code deletes a column from a dataframe in pandas
student_record

   student_id            name
0         101     Divine Odey
1         102   Blessing Odey
2         103   Victory Osang
3         104   Daniel Bullem
4         105    Maxwell Ogon
5         106   Praise Bullem
6         107
7         108  Flourish Osang
8         109      Joel Osang

In [25]:
student_record.loc[0:5,"name"]

0      Divine Odey
1    Blessing Odey
2    Victory Osang
3    Daniel Bullem
4     Maxwell Ogon
5    Praise Bullem
Name: name, dtype: object

The above code cell selects from row from index 0 to index 5 inclusive, and only the name column. The .loc acts a location and remember when we said NumPy is being declared as rows before columns

In [26]:
delivery_data[["delivery_id", "item" ]]
#this selects only the specified columns

   delivery_id    item
0          101    Rice
1          102   Beans
2          103   Garri
3          104  Potato

In [28]:
delivery_data.iloc[:, 0:2]

   delivery_id    item
0          101    Rice
1          102   Beans
2          103   Garri
3          104  Potato

The above code cell uses *iloc* which I guess stands for index location, iloc is last value exclusive and it uses index for the columns instead of name of the column